---
##
# Parse hostnames to grab 1st 2 characters
##
- name: "Parse hostname's 1st 2 characters"
  set_fact: parhost={{ ansible_hostname[0:2] }}

##
# Conditionally set name of checksum binary
##
- name: "set checksum binary"
  set_fact:
    csbin: "{{ 'cksum' if (ansible_distribution == 'RedHat') else 'csum' }}"

##
# Enclose in block so we can use parhost to exclude hosts
##
- block:
   ##
   # Validate will prevent bad files, no need to revert
   ##
   - name: Ensure sudoers file
     copy:
       src: sudoers
       dest: /etc/sudoers
       owner: root
       group: root
       mode: 0440
       backup: yes
       validate: /usr/sbin/visudo -cf %s
     register: sudochg

   ##
   # Ensure line is added to desired hosts
   ##
   - name: Ensure sudoers.d include
     lineinfile:
       path: /etc/sudoers
       line: '#includedir /etc/sudoers.d'
       validate: /usr/sbin/visudo -cf %s
     when: parhost == INCLUDE

   - name: sudoers checksum
     shell: "{{ csbin }} /etc/sudoers >> {{ MD5FILE }}"
     when: sudochg.changed

   - name: Ensure MD5FILE permissions
     file:
       path: "{{ MD5FILE }}"
       owner: root
       group: root
       mode: 0600
       state: file
  ##
  # This conditional restricts what hosts this block runs on
  ##
  when: parhost != EXCLUDE
...
